### ISSUE TITLE
最佳实践概要

### ISSUE THREAD

**Issue by shenruijun** [oss-cn/gp-docs-cn#1]
最佳实践概要，索引部分：
Avoid using bitmap indexes for unique columns, very high or very low cardinality data. Bitmap indexes perform best when the column has a low cardinality—100 to 100,000 distinct values.
译为：不要为唯一列、基数非常高或者非常低的数据使用位图索引。
我个人觉得译为：避免对于唯一列、基数非常高或者选择度非常低的基数数据列使用位图索引。当列的基数很低时（100至100000个不同的值），位图索引性能最佳。

**Comment by vitesse-ftian** [comment]
Similar sentences appear in both schema.html and summary.html -- I assume the summary.html content is properly translated.
